# we need docker
# docker needs sudo 

sudo: required
services:
  - docker

before_install:
  - docker build -t jaqenhghar2402/ci-cd-aws -f Dockerfile .

# commands required for running test suite
# use -- --coverage to make npm run tests and then exit immediately
script:
  - docker run jaqenhghar2402/ci-cd-aws npm run test -- --coverage